forum/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from forum.views import show_forum
from forum.views import show_forum_json 
from forum.views import show_forum_json_by_user
from forum.views import show_comments_json
from forum.views import add_post
from forum.views import add_comment
from forum.views import post_post
from forum.views import post_comment

app_name = 'forum'

urlpatterns = [
    path('', show_forum, name='show_forum'),
    path('json/', show_forum_json, name='show_forum_json'),
    path('json-by-user', show_forum_json_by_user, name='show_forum_json_by_user'),
    path('json-comments/<int:id>/', show_comments_json, name='show_comments_json'),
    path('add-post/', add_post, name='add_post'),
    path('add-comment/<int:id>/', add_comment, name='add_comment'),
    path('post-post-api/', post_post, name='post_post'),
    path('post-comment-api/<int:id>/', post_comment, name='post_comment'),
]

landing_page/urls.py
from django.urls import path
from landing_page.views import logout_user, register, login_user, welcome, feedback, show_json

app_name = 'landing_page'

urlpatterns = [
    path('', welcome, name='welcome'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('json/', show_json, name='show_json'),
    path('feedback/', feedback, name='feedback')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('myaccount/', include('my_account.urls')),
    path('authentication/',include('authentication.urls')),
    path('create-event/', include('create_event.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('welcome/', include('landing_page.urls')),
    path('timeline/', include('timeline.urls')),
    path('forum/', include('forum.urls')),

]

landing_page/models.py
from email.policy import default
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from create_event.models import Event
from timeline.models import JoinEvent

# Create your models here.
class UserAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_point = models.IntegerField(default = 0)
    username = models.CharField(max_length = 63, default = "unknown")
    # import models dari Event
    events_joined = models.ManyToManyField(JoinEvent)

    # post di forum yang author nya user ini bisa langsung cek dari database forum aja

class Feedback(models.Model):
    message = models.TextField()

landing_page/forms.py
from django.forms import ModelForm
from landing_page.models import Feedback

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['message']

landing_page/views.py
from django.shortcuts import render, redirect
from landing_page.models import Feedback, UserAccount
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.core import serializers
from .forms import FeedbackForm
# Create your views here.

def welcome(request):
    if request.user.is_authenticated:
        if not UserAccount.objects.filter(user = request.user).exists(): # check if account already exist
            UserAccount.objects.create(user = request.user, user_point = 0, username = request.user.username)
    return render(request, "welcome.html")

#ini bener gasih buat nyimpen ke database?
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('landing_page:login_user')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def show_json(request):
    show_feedback = Feedback.objects.order_by("?").first()
    return HttpResponse(serializers.serialize("json", show_feedback), content_type="application/json")

@csrf_exempt
def feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"pk" : form.pk, 
                "fields": {
                "message" : form.message
            }})

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            #response = HttpResponseRedirect(reverse("landing_page:welcome")) # membuat response
            #response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return redirect('landing_page:welcome')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    #response = HttpResponseRedirect(reverse('landing_page:login_user'))
    #response.delete_cookie('last_login')
    return redirect('landing_page:welcome')

landing_page/templates/login.html
{% extends 'base.html' %} {% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .center {
            text-align:center; 
        }
        .logintitle {
            color:#483D8B;
            font-size:20px;
            font-weight:bold;
            font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .tabletitle {
            color:#DC143C;
            font-size:20px;
            font-weight:bold;
        }
        .logincontent {
            color:#000000;
            font-size:20px;
            font-weight:bold;
            font-family:Arial, Helvetica, sans-serif
        }
    </style>
</head>
<body style="background-color:#ADD8E6">
    <div class = "login">
        <div>
        <h1 class="logintitle">Log in to Your Account</h1>
    
        <form method="POST" action="">
            {% csrf_token %}
            <div class="center">
            <table class="logincontent">
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
            </div>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Haven't made an account? <a href="{% url 'landing_page:register' %}">Register</a>
        </div>
    </div>
    
</body>

{% endblock content %}

landing_page/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .main {
            text-align:center; 
        }
        .formtitle {
            color:#00008B;
            font-size:20px;
            font-weight:bold;
        }
        .tabletitle {
            color:#DC143C;
            font-size:20px;
            font-weight:bold;
        }
        .tablecontent {
            color:#000000;
            font-size:20px;
            font-weight:bold;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
    </style>
</head>
<body style="background-color:#ADD8E6">
    <div class = "login">
    
        <h1 class="formtitle">Register</h1>  
        <isi class="tablecontent">
                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input type="submit" name="submit" value="Daftar"/></td>  
                        </tr>  
                    </table>  
                </form>
    
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}        
        </isi>
    </div>  
    
</body>

{% endblock content %}

landing_page/templates/welcome.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        .menu {
            grid-area: menu;
        }
        #about {
            background-color: lightgrey;
        }
        .right {
            grid-area: right;
        }
        .btn {
            color: black;
            background-color: lightcyan;
        }
        .btnlight {
            color: black;
            background-color: cyan;
        }
        .center {
            text-align:center; 
        }
        .rtsdesc {
            background-color: lightgrey;
            width: 100%;;
        }
        .box1 {
            width: 380px;
            padding: 10px;
            margin: 10px;
        }

        .img {
            width: 380px;
            height: 380px;
            margin: 10px;
        }
        .imgsmall {
            width: 150px;
            height: 150px;
            margin: 10px;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            width: 100%;
            height: 190px;
            color:#000000;
            background-color: lightcyan;
            font-size:15px;
            font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .largetxt {
            width: 200px;
            height: 100px;
            padding: 5px;
        }
        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }
        .card1 {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
            width: 100%;
            color:#000000;
            padding: 10px;
            background-color: lightgray;
            font-size:15px;
            font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .colthree {
            column-count: 3;
        }

        .coltwo {
            columns: 2;
        }
        
    </style>
</head>
<body>
    <div style="background-image: url('https://image.cnbcfm.com/api/v1/image/107028541-1646934420167-gettyimages-101680465-ac4714a8-f421-4a76-ab21-eaa1793d80c8.jpeg?v=1646934663');">
    <div class="center"><h1 style="background-color:midnightblue; color:white; font-family:'Times New Roman', Times, serif;">Restore the Shore</h1></div>
    {% if request.user.is_authenticated %}
        <div class="center">
        <div class="menu">
        <div class="card1">Hello environmentalists! Beaches have always been an important element for the environment and sea life.
            Restore the Shore is an interactive website where users can participate in events to clean beaches and post about them
            in the website. Users can get points and earn badges for joining events!
        </div>
        <button type="button" class="btn" style="margin:10px">
            <a>See events</a>
        </button>
        </div>
        </div>
        <!--
        <div class="right">
            <img class="imgsmall" src="https://www.travelandleisure.com/thmb/z58cxJrR_0MJRq2cePrO9KUnF9g=/1200x1200/smart/filters:no_upscale()/saud-beach-luzon-philippines-WRLDBEACH0421-15e2c368e7ad4495be803bd60cafa379.jpg" alt="..." />
        </div>-->
        <h2 class="center" style="margin: 30px; color:white; font-family: 'Times New Roman', Times, serif;">
            -------Our Visions-------
        </h2>
        
        <div class="colthree">
        
        <img class="img" src="https://assets2.cbsnewsstatic.com/hub/i/r/2011/06/29/441f00d4-a643-11e2-a3f0-029118418759/thumbnail/640x480/4a3ecbefafd3d851b6b4927bbcf5cd46/dirtybeach_istock_000015037586.jpg" alt="..."/>
        <div class="card">
        <h3 class="center">Make The Shores Clean</h3>
        <div class="box1">Now, lots of beaches contains lots of litter. The litters, like plastic ones, are very dangerous to the envronment and marine life.
            Clean shores makes oceans healthy, also to help preserve marine life.
        </div>
        </div>

        
        <img class="img" src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/beach-quotes-1559667853.jpg" alt="..." />
        <div class="card">
        <h3 class="center">Preserve The Shores</h3>
        <div class="box1">Beaches have been an important part for a lot of sectors. Beaches attract a lot of tourists, which means beaches contribute
            for the economy. Beaches are also the home for some animals and marine life.
        </div> 
        </div>

        
        <img class="img" src="https://www.mecc.gov.qa/wp-content/uploads/2022/09/%D8%AA%D9%86%D8%B8%D9%8A%D9%81-%D8%B4%D8%A7%D8%B7%D9%8A%D9%94-%D8%A7%D8%A8%D9%88%D9%81%D9%86%D8%B7%D8%A7%D8%B3.jpg-2-1024x768.jpg" alt="..." />
        <div class="card">
        <h3 class="center">Raise Awareness to The Importance of Beaches</h3>
        <div class="box1">By participating in these events, participants can raise awareness of the importance of beaches to even more people, so more people will have
            the knowledge and will be more motivated to preserve beaches.
        </div>
        </div>
        </div>

        <div class="center" id="showmessage">
            
        </div>

        <div class="center" style="margin:auto">
            
            <h2 style="color: white">Send a Feedback!</h2>
            <form method="POST" id="new_feedback">
            {% csrf_token %}
            <div>
                <input type="text" name="message" placeholder="Type here..." id="message">
                <input type="submit">
            </div>
            </form>
            
        </div>
        <h5 class="center" style="color: lightgray">© 2022 - Restore The Shore - All rights reserved </h5>
        <h5>...</h5>
    {% else %}
        <div class="center">
        <div class="menu">
        <div class="card1">Hello environmentalists! Beaches have always been an important element for the environment and sea life.
            Restore the Shore is an interactive website where users can participate in events to clean beaches and post about them
            in the website. Users can get points and earn badges for joining events!
        </div>
        <button type="button" class="btn" style="margin:10px">
            <a>See events</a>
        </button>
        <h2></h2>
        <button type="button" class="btnlight">
            <a href="{% url 'landing_page:login_user' %}">Log In</a>
        </button>
        <button type="button" class="btnlight">
            <a href="{% url 'landing_page:register' %}">Register</a>
        </button>
        </div>
        </div>
        <!--
        <div class="right">
            <img class="imgsmall" src="https://www.travelandleisure.com/thmb/z58cxJrR_0MJRq2cePrO9KUnF9g=/1200x1200/smart/filters:no_upscale()/saud-beach-luzon-philippines-WRLDBEACH0421-15e2c368e7ad4495be803bd60cafa379.jpg" alt="..." />
        </div>-->
        <h1 class="center" style="margin: 30px; color:white; font-family: 'Times New Roman', Times, serif;">
            -------Our Visions-------
        </h1>
        
        <div class="colthree">
        
        <img class="img" src="https://assets2.cbsnewsstatic.com/hub/i/r/2011/06/29/441f00d4-a643-11e2-a3f0-029118418759/thumbnail/640x480/4a3ecbefafd3d851b6b4927bbcf5cd46/dirtybeach_istock_000015037586.jpg" alt="..."/>
        <div class="card">
        <h3 class="center">Make The Shores Clean</h3>
        <div class="box1">Now, lots of beaches contains lots of litter. The litters, like plastic ones, are very dangerous to the envronment and marine life.
            Clean shores makes oceans healthy, also to help preserve marine life.
        </div>
        </div>

        
        <img class="img" src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/beach-quotes-1559667853.jpg" alt="..." />
        <div class="card">
        <h3 class="center">Preserve The Shores</h3>
        <div class="box1">Beaches have been an important part for a lot of sectors. Beaches attract a lot of tourists, which means beaches contribute
            for the economy. Beaches are also the home for some animals and marine life.
        </div> 
        </div>

        
        <img class="img" src="https://www.mecc.gov.qa/wp-content/uploads/2022/09/%D8%AA%D9%86%D8%B8%D9%8A%D9%81-%D8%B4%D8%A7%D8%B7%D9%8A%D9%94-%D8%A7%D8%A8%D9%88%D9%81%D9%86%D8%B7%D8%A7%D8%B3.jpg-2-1024x768.jpg" alt="..." />
        <div class="card">
        <h3 class="center">Raise Awareness to The Importance of Beaches</h3>
        <div class="box1">By participating in these events, participants can raise awareness of the importance of beaches to even more people, so more people will have
            the knowledge and will be more motivated to preserve beaches.
        </div>
        </div>
        </div>
        <h5 class="center" style="color:lightgray">© 2022 - Restore The Shore - All rights reserved </h5>
        <h5>...</h5>

    {% endif %}
    </div>
    <script>
        $(document).ready(function(){
            $("#new_feedback").submit(function(e){
            e.preventDefault();
            $.post("/feedback/",{
                message:$("#message").val(),
            }).done(function(e){
                $("#message").val("");
            })
            });
        }
        );
    </script>
</body>
{% endblock content %}