forum/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from forum.views import show_forum
from forum.views import show_forum_json 
from forum.views import show_forum_json_by_user
from forum.views import show_comments_json
from forum.views import add_post
from forum.views import add_comment
from forum.views import post_post
from forum.views import post_comment

app_name = 'forum'

urlpatterns = [
    path('', show_forum, name='show_forum'),
    path('json/', show_forum_json, name='show_forum_json'),
    path('json-by-user', show_forum_json_by_user, name='show_forum_json_by_user'),
    path('json-comments/<int:id>/', show_comments_json, name='show_comments_json'),
    path('add-post/', add_post, name='add_post'),
    path('add-comment/<int:id>/', add_comment, name='add_comment'),
    path('post-post-api/', post_post, name='post_post'),
    path('post-comment-api/<int:id>/', post_comment, name='post_comment'),
]

my_account/urls.py
from django.urls import path
from my_account.views import *

app_name = 'my_account'

urlpatterns = [
    path('', show_account, name='my_account'),
    path('json/', show_json, name = 'show_json'),
    path('change_password/', password_change, name = 'change_password'),
    path('password_change', changePassword, name="password_change"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('myaccount/', include('my_account.urls')),
    path('authentication/',include('authentication.urls')),
    path('create-event/', include('create_event.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('welcome/', include('landing_page.urls')),
    path('timeline/', include('timeline.urls')),
    path('forum/', include('forum.urls')),

]

timeline/urls.py
from django.urls import path
from timeline.views import *

app_name = "timeline"

urlpatterns = [
    path('', show_data, name="show_data"),
   
    path('join-event/<str:nama>', join_event, name='join_event'),
    path('event_detail/<int:pk>/', show_event_by_id, name='show_event_by_id'),
    path('joinevent/', join_event, name='join_event'),
    path('json/', show_json, name = 'show_json'),
    path('json-all/', show_json_all, name = 'show_json_all(request)'),
    path('join-flutter/', join_flutter, name='join_flutter'),

]

my_account/forms.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django import forms

class ChangePasswordForm(PasswordChangeForm):
    old_password: forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1: forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2: forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

my_account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import update_session_auth_hash
from landing_page.models import UserAccount
from timeline.models import JoinEvent
from .forms import ChangePasswordForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='landing_page:login_user')
def show_account(request):  
    data_user = UserAccount.objects.get(user = request.user)
    for event in JoinEvent.objects.filter(user = request.user):
        data_user.events_joined.add(event)
        data_user.save()
    data_user.user_point = data_user.events_joined.count() * 10
    data_user.save()
    context = {
        'user_data' : data_user,
    }
    return render(request, 'my_account.html', context)

@login_required(login_url='landing_page:login_user')
def show_json(request):
    data_user = UserAccount.objects.filter(user = request.user)
    data = data_user[0]
    for event in JoinEvent.objects.filter(user = request.user):
        data.events_joined.add(event)
        data.save()
    data.user_point = data.events_joined.count() * 10
    data.save()
    return HttpResponse(serializers.serialize("json", data_user), content_type="application/json")

def password_change(request):
    form = ChangePasswordForm(user=request.user)
    if request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("my_account:my_account")
    
    return render(request, 'password_change.html', {'form':form})

@csrf_exempt
def changePassword(request):
    form = ChangePasswordForm(user=request.user, data=request.POST)
    if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return JsonResponse({"status" : "success", "message" : "berhasil"})
    return JsonResponse({"status" : "failed", "message" : "gagal"})

    

my_account/templates/my_account.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Account</title>
<style>
  body {
    margin: 0;
    padding: 0;
    background-image: url(https://image.cnbcfm.com/api/v1/image/107028541-1646934420167-gettyimages-101680465-ac4714a8-f421-4a76-ab21-eaa1793d80c8.jpeg?v=1646934663);
  }

  #wrapper {
    width: 100%;
    margin: 0 auto;
  }

  article,
  aside,
  header,
  nav {
    background: rgb(255, 255, 255);
    margin-bottom: 10px;
    text-align: left;
    padding: 1.5vh;
    color: rgb(0, 0, 0);
  }

  header {
    display: flex;
    justify-content: space-between;
  }

  article,
  aside {
    float: left;
    min-height: 100vh;
    height: max-content;
    margin-right: 0.5%;
    margin-left: 0.5%;
    border-radius: 1vh;
  }

  article {
    width: 72%;
  }

  aside {
    width: 26%;
  }

  .row {
    margin: 1vmax;
  }

  .myBadge {
    width: 100%;
    height: 100%;
    margin-bottom: 5px;
  }

  .btn {
    width: auto;
  }

  .btn-primary {
    background-color: #6366F1;
  }

  .flex-container {
    display: flex;
    flex-direction: row;
  }

/* Responsive layout - makes a one column layout instead of a two-column layout */
  @media (max-width: 800px) {
    .flex-container {
      flex-direction: column;
    }

    article, aside {
      width: 96%;
      margin: 1% 2% 1% 2%;
    }
  }

  #congrats {
    font-size: medium;
    margin-top: 2%;
    text-align: center;
  }

  #member-class {
    font-weight: bold;
    font-size: large;
  }

  #point {
    font-size: large;
  }

  #change-pass {
    margin-top: 1vh;
  }

</style>
{% endblock meta %}


{% block content %}
<script>
  $(document).ready(function () {
    $.ajax({
      url: "{% url 'forum:show_forum_json_by_user' %}",
      dataType: 'json',
      success: function (data) {
        for (var i = 0; i < data.length; i++) {
          $("#my-posts").append(
                    `
                    <div class = "row" style="margin:5px;">
                      <div class="card" id="post-${data[i].pk}" style="outline:black;">
                        <div class="card-header">${data[i].fields.creator.name}</div>
                        <div class="card-body">
                          <img src="${data[i].fields.image}" class="post-image" style="max-width:100%;"/>
                          <p class="card-content">${data[i].fields.content}</p>
                        </div>
                        <div class="card-footer text-muted">Posted on ${data[i].fields.date}</div>
                      </div>
                    </div>
                    `
          );
        }
        if (i == 0) {
          $("#my-posts").append(`
          <a type="button" class="btn btn-primary mx-auto" href="{% url 'forum:show_forum' %}">Post Something</a>
          <br>
          <h5 class="text-muted font-weight-light"> You haven't post anything </h5>
          <br>
          `);
        }
      },
    });
  });
</script>

<div id="wrapper">
  <header>
    <div>
      <h1>Hi {{user.get_username}},</h1>
    </div>
    <div>
      <a type="button" class="btn btn-primary mx-auto" id="change-pass" href="{% url 'my_account:change_password' %}">Change Password</a>
    </div>
  </header>
  <!-- My Posts -->
  <div class="flex-container">
    <article id="article">
      <h3>My Posts</h3>
      <hr style="border-top: 2px dashed;">
    <div 
    class="my-posts column h-100 d-flex align-items-center justify-content-center" 
    id="my-posts"
        style="flex-direction:column-reverse;"
    >
    </div>
      
  </article>
  <aside id="aside">
  <!-- Show Badges -->
    <h3>Badge</h3>
    <p id="point">Point : {{user_data.user_point}}</p>
    <div class="container">
      {% if user_data.user_point >= 200 %}
        <div class="col">
          <img id="platinum" class="myBadge" src="{% static 'platinum.png' %}" alt="paltinum">
          <p id="congrats">Congrats, You are a <span id="member-class">Platinum</span> Member</p>
        </div>
        {% elif user_data.user_point >= 150 %}
        <div class="col">
          <img id="gold" class="myBadge" src="{% static 'gold.png' %}" alt="gold">
          <p id="congrats">Congrats, You are a <span id="member-class">Gold</span> Member</p>
        </div>
        {% elif user_data.user_point >= 100 %}
        <div class="col">
          <img id="silver" class="myBadge" src="{% static 'silver.png' %}" alt="silver">
          <p id="congrats">Congrats, You are a <span id="member-class">Silver</span> Member</p>
        </div>
        {% elif user_data.user_point >= 50 %}
        <div class="col">
          <img id="bronze" class="myBadge" src="{% static 'bronze.png' %}" alt="bronze">
          <p id="congrats">Congrats, You are a <span id="member-class">Bronze</span> Member</p>
        </div>
        {% else %}
        <h5 class="text-muted" style="text-align: center;">You need more Points</h5>
        {% endif %}
        
      </div>
      
      <!-- Show Event History -->
      <hr style="border-top: 2px dashed;">
      <h5>Event History</h5>
      {% if user_data.events_joined.all.count == 0 %}
      <div class="column h-100 d-flex align-items-center justify-content-center flex-column">
        <h5 class="text-muted row font-weight-light" style="text-align: center;">You haven't joined any event</h5>
        <a type="button" class="btn btn-primary mx-auto row" href="{% url 'timeline:show_data' %}">Find Events</a>
      </div>
      <div>      
        
      </div>
      {% else %}
      <p>You have joined {{user_data.events_joined.all.count}} event(s)</p>
      {% endif %}
      <div id="myEvent" class="column d-flex align-items-center justify-content-center flex-column">
        {% for event in user_data.events_joined.all %}
        <div class="row">
          <div class="card">
            <div class="card-body" style="font-weight: bold;">
              <p>{{event.namaEvent}} @{{event.namaPantai}}</p>
            </div>
            <div class="card-footer text-muted">{{event.tanggalMulai}} - {{event.tanggalAkhir}}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </aside>
  </div>
</div>
  


{% endblock content %}

my_account/templates/password_change.html
{% extends 'base.html' %}

{% block meta %}
<title>Change Password</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
{% endblock meta %}

{% block content %}  
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .btn-secondary {
            background-color: #6366F1;
        }

        #back-btn {
            margin-left: 3vh;
        }
    </style>
</head>
<body style="background-color:rgb(255, 255, 255)">
    <a type="button" id="back-btn" class="btn btn-secondary" href="{% url 'my_account:my_account' %}">
        Back
    </a>
    <div class = "change-password">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                <div class="col-md-6 offset-md-3">
                    <span class="anchor" id="formChangePassword"></span>
                    <br>
                    <br>
                    <!-- form card change password -->
                    <div class="card card-outline-secondary">
                        <div class="card-body">
                            <h2 class="mb-0">Change Password</h2>
                            <br>
                            <div class="form-group">
                                <label for="id_old_password">Old password</label>
                                <input class="form-control" type="password" name="old_password" autocomplete="current-password" autofocus required id="id_old_password">  
                            </div>
                            <div class="form-group">
                                <label for="id_new_password1">New password</label>
                                <input class="form-control" type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1">
                                <span class="helptext">
                                    <span class="form-text small text-muted"> The password must be 8-20 characters, and must <em>not</em> contain spaces. </span>
                                </span>
                            </div>
                            <div class="form-group">
                                <label for="id_new_password2">Verify Password</label>
                                <input class="form-control" type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-secondary btn-lg float-right">Change Password</button>
                            </div>
                        </div>
            </form>
        </div>
    </div>  
    
</body>

{% endblock content %}