create_event/urls.py
from django.urls import path
from create_event.views import show_create_event
from create_event.views import add_event
from create_event.views import show_json, delete_event, show_more_info, add_event_mobile

app_name = "create_event"

urlpatterns = [
    path('', show_create_event, name="show_create_event"),
    path('add/', add_event, name="add_event"),
    path('add-mobile/', add_event_mobile, name="add_event_mobile"),
    path('json/', show_json, name = 'show_json'),
    path('delete-event/<int:id>/', delete_event, name = 'delete_event'),
    path('show-info/<int:id>/', show_more_info, name = 'show_info'),
]

forum/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from forum.views import show_forum
from forum.views import show_forum_json 
from forum.views import show_forum_json_by_user
from forum.views import show_comments_json
from forum.views import add_post
from forum.views import add_comment
from forum.views import post_post
from forum.views import post_comment

app_name = 'forum'

urlpatterns = [
    path('', show_forum, name='show_forum'),
    path('json/', show_forum_json, name='show_forum_json'),
    path('json-by-user', show_forum_json_by_user, name='show_forum_json_by_user'),
    path('json-comments/<int:id>/', show_comments_json, name='show_comments_json'),
    path('add-post/', add_post, name='add_post'),
    path('add-comment/<int:id>/', add_comment, name='add_comment'),
    path('post-post-api/', post_post, name='post_post'),
    path('post-comment-api/<int:id>/', post_comment, name='post_comment'),
]

leaderboard/urls.py
from django.urls import path
from leaderboard.views import show_leaderboard, show_json, search, add_quote, get_quote, add_quote_mobile
from django.conf import settings 
from django.conf.urls.static import static 


app_name = 'leaderboard'

urlpatterns = [
    path('', show_leaderboard, name='show_leaderboard'),
    path('json/', show_json, name='show_json'),
    path('search/<str:searchusername>/', search, name='search'),
    path('add-quote/', add_quote, name='add_quote'),
    path('get-quote/', get_quote, name='get_quote'),
    path('add-quote-mobile/', add_quote_mobile, name='add_quote_mobile'),
    # path('getuser/<int:id>/', get_user, name='get_user'),
]

my_account/urls.py
from django.urls import path
from my_account.views import *

app_name = 'my_account'

urlpatterns = [
    path('', show_account, name='my_account'),
    path('json/', show_json, name = 'show_json'),
    path('change_password/', password_change, name = 'change_password'),
    path('password_change', changePassword, name="password_change"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('myaccount/', include('my_account.urls')),
    path('authentication/',include('authentication.urls')),
    path('create-event/', include('create_event.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('welcome/', include('landing_page.urls')),
    path('timeline/', include('timeline.urls')),
    path('forum/', include('forum.urls')),

]

timeline/urls.py
from django.urls import path
from timeline.views import *

app_name = "timeline"

urlpatterns = [
    path('', show_data, name="show_data"),
   
    path('join-event/<str:nama>', join_event, name='join_event'),
    path('event_detail/<int:pk>/', show_event_by_id, name='show_event_by_id'),
    path('joinevent/', join_event, name='join_event'),
    path('json/', show_json, name = 'show_json'),
    path('json-all/', show_json_all, name = 'show_json_all(request)'),
    path('join-flutter/', join_flutter, name='join_flutter'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <link rel="shortcut icon" href="#">

  {% block meta %}
  {% endblock meta %}
</head>

<div>
  {% if request.user.is_superuser %}
  <!-- Mengakses semua modul, ditambah create event-->
  <nav style=
    "
      position: fixed;
      display: flex;
      top: 0px;
      z-index: 200;
      width: 100%;
      box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
      padding-left: 20px;
      padding-right: 20px;
    "
    class="navbar navbar-white bg-white navbar-expand-lg fixed-top">
    <img src="https://user-images.githubusercontent.com/97111982/198334048-2fbdb0b7-b663-40dc-91fa-45325b5927d2.png" width="100" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <img src="https://static.thenounproject.com/png/633488-200.png" width="30" alt="">
    </button>
    <div class="collapse navbar-collapse visible" id="navbarNav">
      <ul style="
      display: flex;
      width: 100%;
      justify-content: flex-end;" 
      class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:welcome' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'timeline:show_data' %}">Timeline</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_event:show_create_event' %}">Create Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forum:show_forum' %}">Forum</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'leaderboard:show_leaderboard' %}">Leaderboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_account:my_account' %}">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:logout_user' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  {% elif request.user.is_authenticated %}
  <!-- Mengakses semua modul dari guest user ditambah dengan my account, forum -->
  <nav style=
    "
      position: fixed;
      display: flex;
      top: 0px;
      width: 100%;
      box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
      padding-left: 20px;
      padding-right: 20px;
    "
    class="navbar navbar-white bg-white navbar-expand-lg fixed-top">
    <img src="https://user-images.githubusercontent.com/97111982/198334048-2fbdb0b7-b663-40dc-91fa-45325b5927d2.png" width="100" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <img src="https://static.thenounproject.com/png/633488-200.png" width="30" alt="">
    </button>
    <div class="collapse navbar-collapse visible" id="navbarNav">
      <ul style="
      display: flex;
      width: 100%;
      justify-content: flex-end;" 
      class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:welcome' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'timeline:show_data' %}">Timeline</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forum:show_forum' %}">Forum</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'leaderboard:show_leaderboard' %}">Leaderboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_account:my_account' %}">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:logout_user' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  {% else %}
  <!-- Mengakses modul landing page, register, login, timeline, dan leaderboard -->
  <nav style=
    "
      position: fixed;
      display: flex;
      top: 0px;
      z-index: 200;
      width: 100%;
      box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
      padding-left: 20px;
      padding-right: 20px;
    "
    class="navbar navbar-white bg-white navbar-expand-lg fixed-top">
    <img src="https://user-images.githubusercontent.com/97111982/198334048-2fbdb0b7-b663-40dc-91fa-45325b5927d2.png" width="100" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <img src="https://static.thenounproject.com/png/633488-200.png" width="30" alt="">
    </button>
    <div class="collapse navbar-collapse visible" id="navbarNav">
      <ul style="
      display: flex;
      width: 100%;
      justify-content: flex-end;" 
      class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:welcome' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'timeline:show_data' %}">Timeline</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'leaderboard:show_leaderboard' %}">Leaderboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:login_user' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'landing_page:register' %}">Register</a>
        </li>
      </ul>
    </div>
  </nav>
  {% endif %}
</div>

<body style="padding-top:80px;">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  {% block content %}
  {% endblock content %}
</body>

</html>